- name: Setup backupninja
  hosts: all
  
  pre_tasks: 
    - name: Add vim
      yum: 
        name: vim
        state: present
            

  roles:
    - role: backupninja
    - role: duplicity
    - role: vkill.gpg_key
      tags: gpg
